version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: maria
      MARIADB_USER: maria
      MARIADB_PASSWORD: maria
      MARIADB_DATABASE: db
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
